### ISSUE TITLE
Seeded candles missing recent prices when backtesting in live mode

### ISSUE THREAD

**Issue by leugueg** [bitfinexcom/bitfinex-api-py#101]
#### Issue type
- [x ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Seeding call doesn't retrieve all candles up to now - in bfx_rest.py
#### Steps to reproduce
-

##### Additional Notes:
In async def get_seed_candles(self, symbol, tf='1m')
use **end = now - (x * time_difference)** instead of **end = now - (x * time_difference) - time_difference**

**Comment by itsdeka** [comment]
@prdn this can be closed, fixed in last update
