### ISSUE TITLE
Order book silently stops receiving data

### ISSUE THREAD

**Issue by DmitriyG228** [bitfinexcom/bitfinex-api-py#107]
#### Issue type
- [x ] bug

#### Brief description
Order book silently stops receiving data after like half an hour. 

I might be missing something obvious since I am new to async programming, sorry about that

#### Steps to reproduce
I develop in Jupiter notebook

i am getting order book with `bfx.ws.orderBooks['tBTCUSD'].asks`

and after I stopped receiving updates and run `await bfx.ws.subscribe('book', 'tBTCUSD')` I get the following error:

`ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason`

-

##### Additional Notes:
-

**Comment by itsdeka** [comment]
Thanks @DmitriyG228, I am trying to reproduce the error on my end

**Comment by itsdeka** [comment]
Hello @DmitriyG228, I can't reproduce it.
It keeps receiving updates.

I'll try to launch it in a Jupiter notebook.

**Comment by DmitriyG228** [comment]
@itsdeka, thank you, I have currently switched to acquiring order book via REST, but I will get back to this issue later and post here if I find he bug.
