### ISSUE TITLE
[BfxWebsocket] [ERROR] Notification ERROR: compliance: restricted (unverified)

### ISSUE THREAD

**Issue by jsphon** [bitfinexcom/bitfinex-api-py#108]
Hello,
I'm trying to place a live order using the API. I can successfully place orders via the website. But when using the API, I receive this error:
`
[BfxWebsocket] [ERROR] Notification ERROR: compliance: restricted (unverified)`

I am using a Sub Account with Basic Verification. My main account has full verification.

What could I be doing wrong? Do I need to fully verify the sub account?

My source code is here:

```
import os
import sys

sys.path.append('../../../')

from bfxapi import Client, Order


bfx = Client(
  API_KEY=BITFINEX_KEY,
  API_SECRET=BITFINEX_SECRET,
  logLevel='DEBUG'
)

@bfx.ws.on('order_snapshot')
async def cancel_all(data):
  await bfx.ws.cancel_all_orders()

@bfx.ws.on('order_confirmed')
async def trade_completed(order):
  print ("Order confirmed.")
  print (order)


@bfx.ws.on('error')
def log_error(msg):
  print ("Error: {}".format(msg))

@bfx.ws.on('authenticated')
async def submit_order(auth_message):
  print('submiting order')
  result = await bfx.ws.submit_order('tKANUSD', 430, 0.0001, Order.Type.EXCHANGE_LIMIT)
  print(result)
  print('finished submission')

# If you dont want to use a decorator
# ws.on('authenticated', submit_order)
# ws.on('error', log_error)

# You can also provide a callback
# await ws.submit_order('tBTCUSD', 0, 0.01,
# 'EXCHANGE MARKET', onClose=trade_complete)

bfx.ws.run()
```

**Comment by itsdeka** [comment]
Hello @jsphon,
there shouldn't be any difference between placing an order through the website and the API. 
Sub-accounts can share verification with the main account, if enabled. They can be verified separately, but don't necessarily need to given the fact that verification can be shared.

**Comment by itsdeka** [comment]
Hello @jsphon,
there shouldn't be any difference between placing an order through the website and the API.
Sub-accounts can share verification with the main account, if enabled. They can be verified separately, but don't necessarily need to given the fact that verification can be shared.

Please note the sub account does need verification to trade on certain pairs (including tKANUSD). A sub-account can be verified separately, or it can share verification with the main account. To share verification with their sub account, they need to toggle on verification sharing on the main account.

If you are not able to solve the issue with this advice, it may be something account specific. In that case, please open a support ticket.

**Comment by jsphon** [comment]
Hello @itsdeka . The problem went away after I waited a bit before placing the order. I think the API diesn't like it if I place orders immediately after authentication.
