### ISSUE TITLE
Insufficient funds error when trying to place an order using project examples

### ISSUE THREAD

**Issue by goodglitch** [bitfinexcom/bitfinex-api-py#109]
#### Issue type
- [*] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
When I try to place an order using examples from the project API returns: 
"Notification ERROR: Invalid order: not enough exchange balance for 1 BTCUSD at 55". 

I double checked that there are 60$ at the exchange account. I increased an amount, since thought that there may be restrictions for order to be bigger than 50$. When I run get_authenticated_data.py from examples folder I see 60$ at the exchange wallet: 
"Wallet <'exchange_USD' balance='60.0000000149' unsettled='0' available='60.0000000149'>"

I can create such an order through web interface, but I can not do it neither through REST nor websocket interfaces.

#### Steps to reproduce
Run any example that places an order.

##### Additional Notes:
-

**Comment by itsdeka** [comment]
Hello @goodglitch, I reproduced the exact scenario on my end and it works as expected.

This is the line of code I used to send the order while having 50$ in EXCHANGE USD wallet

response = await bfx.rest.submit_order("tBTCUSD", 50, 1, market_type=Order.Type.EXCHANGE_LIMIT)

**Comment by goodglitch** [comment]
Hey @itsdeka! Thank you very much for the reply! 

Indeed adding "market_type=Order.Type.EXCHANGE_LIMIT" helped with the rest interface example. I wonder why it is missing in the example files. 

However, example file for ws does contain Order.Type.EXCHANGE_LIMIT, but it still does not work. So when I am trying to execute 

await bfx.ws.submit_order('tBTCUSD', 50, 1, Order.Type.EXCHANGE_LIMIT) 

I still get an error that says insufficient funds. Just in case I also tried:

await bfx.ws.submit_order('tBTCUSD', 50, 1, market_type=Order.Type.EXCHANGE_LIMIT)

No luck.

**Comment by goodglitch** [comment]
Just in case this the part of output that ws example produces

[BfxWebsocket] [INFO] Authentication successful.
[BfxOrderManager] [INFO] Order cid=1614099792988 (tBTCUSD 1 @ 50) dispatched
[BfxWebsocket] [DEBUG] [0,"n",[1614099801081,"on-req",null,null,[null,null,1614099792988,"tBTCUSD",null,null,1,null,"EXCHANGE LIMIT",null,null,null,0,null,null,null,50,null,0,0,null,null,null,0,0,null,null,null,null,null,null,{}],null,"ERROR","Invalid order: not enough exchange balance for 1 BTCUSD at 50"]]
[BfxWebsocket] [ERROR] Notification ERROR: Invalid order: not enough exchange balance for 1 BTCUSD at 50

**Comment by jsphon** [comment]
@goodglitch, I had a similar problem while running some example code.
It went away after I waited a second before placing the order.

e.g.

`await asyncio.sleep(1.0)`
