### ISSUE TITLE
Post only orders returning success

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#111]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
In submitting an order of post-only type , it seems that the status is always successful regardless of whether the order was actually filled or canceled. This is in conflict with the status received via REST directly, which is 'POSTONLY CANCELLED'

Given that this is not reflected in the status itself, I don't see how one could figure out whether the order was cancelled or not. Is there any other way? Am I missing something here?

#### Steps to reproduce
-
```
from bfxapi import Client
bfx = Client(API_KEY='', API_SECRET='')
ret = await bfx.rest.submit_order(symbol='tBTCUSD', price=6000000, amount=0.0002, market_type='LIMIT', post_only=True)
print(ret.status)
'SUCCESS'
```
##### Additional Notes:
-

**Comment by itsdeka** [comment]
Hello jazarija, the request status has nothing to do with the order status. 
If the API keys are correct and the parameters make sense you will always receive a SUCCESS message. You can get the details of the order looking into ret.notify_info.

See this example

`async def test():
  req = await bfx.rest.submit_order(symbol='tBTCUSD', price=6000000, amount=0.0002, market_type='LIMIT', post_only=True)
  order = req.notify_info[0]
  print(f"Order {order.id} | Status: {order.status} | Price: {order.price} | Amount: {order.amount}")

  history = await bfx.rest.get_order_history('tBTCUSD', limit=1, sort=-1, start=None, end=None)
  last_order = history[0]
  print(f"Order {last_order.id} | Status: {last_order.status} | Price: {last_order.price} | Amount: {last_order.amount}")
`

Output

> Order 1223590064 | Status: ACTIVE | Price: 6000000 | Amount: 0.0002
> Order 1223590064 | Status: POSTONLY CANCELED | Price: 6000000 | Amount: 0.0002
