### ISSUE TITLE
confirm_order_new not called when using api

### ISSUE THREAD

**Issue by jsphon** [bitfinexcom/bitfinex-api-py#112]
#### Issue type
- [ x] bug

#### Brief description

I am testing some code using a paper trading account.

This code does not seem to get called when the API places orders. As a result, I end up with a lot of pending orders.

https://github.com/bitfinexcom/bitfinex-api-py/blob/729019b4c492a822d7074a8d21e274a3fbc6fab7/bfxapi/websockets/order_manager.py#L78-L88

However, the code does get called if I place an order using the API.

#### Steps to reproduce

- I placed a fill or kill and limit orders with  reproduce this. It appears to occur whether or not the order gets filled.

##### Additional Notes:
-

**Comment by jsphon** [comment]
I produced this example, to reproduce the error. However, confirm_order_new is now being called (when I experienced the problem last night, I was using more complex code that is too long to post here):

```
import asyncio
import sys

sys.path.append('../../../../')

from bfxapi import Client, Order


bfx = Client(
  API_KEY=BITFINEX_KEY_TEST,
  API_SECRET=BITFINEX_SECRET_TEST,
  logLevel='DEBUG'
)


@bfx.ws.on('error')
def log_error(msg):
  print ("Error: {}".format(msg))


@bfx.ws.on('authenticated')
async def submit_order(auth_message):
  await asyncio.sleep(0.2)
  await bfx.ws.submit_order('tTESTBTC:TESTUSD', 1, 100, Order.Type.EXCHANGE_LIMIT)
  await asyncio.sleep(0.01)
  await bfx.ws.submit_order('tTESTBTC:TESTUSD', 2, 50, Order.Type.EXCHANGE_LIMIT)
  await asyncio.sleep(0.01)
  await bfx.ws.submit_order('tTESTBTC:TESTUSD', 4, 25, Order.Type.EXCHANGE_LIMIT)

  await asyncio.sleep(1)

  print('=== Submit Order Finished ===')
  print('Pending Order Count:', len(bfx.ws.orderManager.pending_orders))
  print(bfx.ws.orderManager.pending_orders)
  print(bfx.ws.pendingOrders)


@bfx.ws.on('order_confirmed')
async def trade_completed(order):
  print('=== Order Confirmed ===')
  print ("Order confirmed, order_id=", order.id)
  print (order)
  print('Pending Order Count:', len(bfx.ws.orderManager.pending_orders))
  print('Pending Order Ids:', sorted(order for order in bfx.ws.orderManager.pending_orders))



bfx.ws.run()
```

Alas, the pending orders don't seem to get deleted here either.

I believe it is because in these lines, the code attempts to delete the orders by `order.id` instead of `order.cid`:

https://github.com/bitfinexcom/bitfinex-api-py/blob/729019b4c492a822d7074a8d21e274a3fbc6fab7/bfxapi/websockets/order_manager.py#L81

On a slightly unrelated note, I can't see usage of `BfxWebsocket.pending_orders`. Can it be removed?

**Comment by itsdeka** [comment]
Hello @jsphon, thank you very much for your suggestion.
I opened a PR.

**Comment by robertkowalski** [comment]
fixed in https://github.com/bitfinexcom/bitfinex-api-py/pull/114 :)

**Comment by jsphon** [comment]
Thank you both for fixing this! You have an amazing codebase!
