### ISSUE TITLE
get_order_history returning orders from the past

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#116]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
This issue is related to https://github.com/bitfinexcom/bitfinex-api-py/issues/111#issuecomment-792004464 where I was asking how to properly detect if a post-only order landed in the orderbook or is canceled. In the presented solution one has to access the order history book and see what happened to the order. 

Unfortunately, if an order lands in the order book there is no historical record. In particular, it seems as if the get_order_history is returning inconsistent results. Sometimes the last order does not match the actual last order, and even restricting the search with the start parameter gives incorrect results. Consider the following example

```
from bfxapi import Client
bfx = Client(API, KEY)
ret = await bfx.rest.submit_order(amount=0.0002, price=1, symbol='tBTCUSD', post_only=True)
mts = ret.notify_info[0].mts_create
L = await bfx.rest.get_order_history(symbol='tBTCUSD', start=mts, end=None, limit=1, sort=-1)
L[0].mts_create > mts
False
L[0].mts_update > mts
False
```

In this case the order book goes directly into the book and is not registered as a historical order. The returned order is a "random" one whose execution was way before our order was posted.

What is more, sometimes (this is not 100% reproducible) querying for all orders with a starting date far in the future, returns some historical records

```
[L = await bfx.rest.get_order_history(symbol='tBTCUSD', start=1916087019657, end=None, limit=1, sort=-1)
[<bfxapi.models.order.Order at 0x7efc8cb7ab80>]
print(L[0])
Order <'tBTCUSD' amount_orig=0.0002 amount_filled=0.0 mts_create=1616086389000 status='CANCELED' id=60750038057>]
```

This final result is inconsistent, as sometimes get_order_history correctly returns an empty list

```
L = await bbfx.rest.get_order_history(symbol='tBTCUSD', start=1916087019657, end=None, limit=1, sort=-1)
L
[]
```

I am not sure what is causing these results, but so far I am getting quite inconsistent results trying to obtain history about the last submitted order.

**Comment by itsdeka** [comment]
Hello @jazarija,
get_order_history() returns only the cancelled or executed orders, not the pending ones.
The orders created by your code are not cancelled, you should increase their price.

Try with the following snippet

`async def create_order():
  req = await bfx.rest.submit_order(amount=1, price=65432, symbol='tBTCUSD', post_only=True)
  p_order = req.notify_info[0]
  history = await bfx.rest.get_order_history(symbol='tBTCUSD', start=None, end=None, limit=5, sort=-1)
  print(
    f"Datetime {datetime.fromtimestamp(p_order.mts_create / 1000)} | Order {p_order.id} | Amount {p_order.amount} | Price {p_order.price}")
  print('...')
  for order in history:
    print (f"Datetime {datetime.fromtimestamp(order.mts_create / 1000)} | Order {order.id} | Amount {order.amount} | Price {order.price}")
`

Output

`Datetime 2021-03-21 12:25:42.770000 | Order 1225398322 | Amount 1 | Price 65432
...
Datetime 2021-03-21 12:25:43 | Order 1225398322 | Amount 1 | Price 65432
Datetime 2021-03-21 12:25:27 | Order 1225398321 | Amount 1 | Price 51234
Datetime 2021-03-21 12:25:14 | Order 1225398320 | Amount 1 | Price 51234
Datetime 2021-03-21 12:24:40 | Order 1225398319 | Amount 0.55 | Price 50000
Datetime 2021-03-21 12:24:23 | Order 1225398318 | Amount 0.55 | Price 50000
`

**Comment by jazarija** [comment]
Hey there Dario,

I am still confused. How come get_order_history()  with a specified start time, returns orders whose execution was way before start?

**Comment by itsdeka** [comment]
@jazarija I agree, it looks strange. I asked for a review of this thread.

**Comment by itsdeka** [comment]
Hello @jazarija, I agree with your view.
I have asked for a review of this thread, I suspect there could be something strange with the dates filter.
I will update you as soon as possible and I will open a PR to add the 'id' parameter to get_order_history().
Doing so it will be possible to retrieve specific orders by their ids, as documented here (https://docs.bitfinex.com/reference#rest-auth-orders-history).

**Comment by itsdeka** [comment]
Hello @jazarija, I have opened the PR (https://github.com/bitfinexcom/bitfinex-api-py/pull/121).
We were right about the strange behaviour of the start parameter filter, a patch will arrive as soon as possible.
Thanks again for your help.

**Comment by itsdeka** [comment]
Hello @jazarija, the patch has been released.

**Comment by itsdeka** [comment]
Hello @jazarija, the patch has been released.
