### ISSUE TITLE
Internal server error (nonce: small) when using the API

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#120]
#### Issue type
- [ x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I have a trading bot that is implemented in the following (schematic) fashion

```
from bfxapi import Client
bfx = Client(API, KEY)
while True:
     # Do some stuff with bfx & sleep some
```

What I've noticed is that the bot would work fine, but then occasionally everything would break down raising the following exception

```
  File "/home/azi/.local/lib/python3.8/site-packages/bitfinex/rest/restv2.py", line 1217, in active_orders
    response = self._post(path, "", verify=True)
  File "/home/azi/.local/lib/python3.8/site-packages/bitfinex/rest/restv2.py", line 109, in _post
    raise BitfinexException(response.status_code, response.reason, content)
bitfinex.rest.restv2.BitfinexException: (500, 'Internal Server Error', ['error', 10114, 'nonce: small'])
```
In this specific example the exception is raised in active_orders, although I am sure I've seen it raised in other methods as well.
Once this happens, the API key is gone and trying to use it raises the same issue (nonce:small). In order to mitigate this one has to generate a new API key pair.

I am not sure what is causing this but would like to hear how to mitigate/avoid this issue? Its kinda unconformable to leave a bot running and not knowing if the stops/exits were executed.

#### Steps to reproduce
Unfortunately, this happens sporadically and I am not able to give concrete steps that would reproduce this issue. In general, however, it happens when one is using the authenticated REST interface for a while. Also, I've noticed through google that others had the same issue.

##### Additional Notes:
-

**Comment by itsdeka** [comment]
Hello @jazarija, thank you for reporting this.

It is possible that you are trying to do multiple requests at the same time or using the same API key for multiple bots/apps?

**Comment by itsdeka** [comment]
This can also happen if you multiple the timestamp with a larger number e.g. 10000, and when you try to make requests with a nonce like timestamp * 1000 it would fail

**Comment by jazarija** [comment]
Hey there @itsdeka ,

every bot is running on a separate subaccount and has its own API key that is not used by anything else.

As far as the timestamp remark goes I am not sure (~99%) I am doing any timestamp manipulation in the code but will take a closer look. Specifically, the line that triggered the exception above is

`L = [l for l in self.bfx.active_orders() if l[3] == 'tBTCUSD']`

I am not sure how any timestamps could've affected this part.

Also, does it make sense that the API key then become worthless (i.e one cannot connect to the rest interface without creating a new key pair)

**Comment by itsdeka** [comment]
Hello @jazarija, I've opened a PR 

https://github.com/bitfinexcom/bitfinex-api-py/pull/122

**Comment by jazarija** [comment]
Hey there,

thank you for resolving this issues so promptly. The Bitfinex team is doing by far the best job in the exchange space!

I am closing this issue so we can focus on #122
