### ISSUE TITLE
Orders with same timestamp are not sorted properly

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#124]
#### Issue type

- [X] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
When using get_public_trades with sort=1, the orders are not sorted properly whenever there are multiple trades occurring at the same time. I've sent this issue to your support team a while ago but it would be nice to have a fix on the interface level as well. 

#### Steps to reproduce
Consider the 1H BTCUSD candle starting on Sun Apr 04 2021 07:00:00UTC. Its open price is 57394.61698309 as confirmed by the UI chart and the interface call to get_public_candles

```
from bfxapi import Client
bfx = Client()
await bfx.rest.get_public_candles(start=1617519600000, symbol='tBTCUSD', end=None, tf='1h')
[[1617523200000, 57600, 57552, 57620, 57452, 106.38635248],
 [1617519600000, 57394.61698309, 57600, 57600, 57208.977959, 184.08185904]]
```

In theory, if we take the first trade with a start time >= 1617519600000, its price should be  57394.61698309. This is not the case, however:

```
await bfx.rest.get_public_trades(start=1617519600000, limit=1, symbol='tBTCUSD', end=None, sort=1)
[[657815316, 1617519628060, 0.00010805, 57397.32687546]]
```

The problem is that multiple orders occur at 1617519628060 and the returned result is not sorted by order id's 

```
await bfx.rest.get_public_trades(start=1617519600000, limit=10, symbol='tBTCUSD', end=None, sort=1)
[[657815316, 1617519628060, 0.00010805, 57397.32687546],
 [657815314, 1617519628060, 0.0002, 57397.25022924],
 [657815311, 1617519628060, 0.0002, 57397],
 [657815312, 1617519628060, 0.0002, 57397.1267046],
 [657815309, 1617519628060, 0.0002, 57396.423578],
 [657815308, 1617519628060, 0.0002, 57396],
 [657815304, 1617519628060, 0.0002, 57395.86722962],
 [657815306, 1617519628060, 0.0002, 57395.95077494],
 [657815302, 1617519628060, 0.0002, 57395.52028055],
 [657815300, 1617519628060, 0.0002, 57394.77484528]]
```

Note how the order on order ID's is arbitrary.

We see that in order to get the right order we need to manually sort by ID's as well

sorted(await bfx.rest.get_public_trades(start=1617519600000, limit=10, symbol='tBTCUSD', end=None, sort=1))[0]
[657815300, 1617519628060, 0.0002, 57394.77484528]

##### Additional Notes:

-  A quick fix for this issue would be that if get_public_trades is called with ​sort=1, the orders get sorted by ID's. The real fix is to change the REST response directly though.

- Getting the first trade is useful to get the candle open/close price. As is, if one wants to get the opening/closing price at a given time, one has to wait up to 30s before calling the get_public_candles interface. Otherwise the result is wrong due to lag/latency of the candle interface. I am not sure why this is happening only on the candle interface but its really unfortunate.

**Comment by itsdeka** [comment]
Hello @jazarija, thank you for your help.
I opened a PR proposal, but it could be the case to fix it in the REST response.

**Comment by jazarija** [comment]
@itsdeka 

Thank you. 

Indeed, it seems like it really is sensible to change the REST response - otherwise one still cannot obtain the "first trade that happened at time t" without having to fetch the entire local history of trades.

The patch you proposed fixes the issue as far as the python API is concerned so I am closing this down. I hope the developers can fix the rest interface as well!
