### ISSUE TITLE
exception in a thread after websocket reconnects and try to resubscribe

### ISSUE THREAD

**Issue by slurpxbt** [bitfinexcom/bitfinex-api-py#133]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Websocket get 1006 error from time to time...then it reconnects succesfully and try to resubscribe. When it tries to resubscribe it gets exception in a thread and it doesn't close itself

is there a way to completely shut down websocket when exception happens so my script can restart itself(when I manually restart it works fine)

tried this to stop ws but it doesn't work:
```
@bfx.ws.on("error")
async def stop_ws()
     await bfx.ws.stop()
```

treaceback: 

`[�[1m�[90mBfxWebsocket�[0m�[0m] [�[91mERROR�[0m] code = 1006 (connection closed abnormally [internal]), no reason [�[1m�[90mBfxWebsocket�[0m�[0m] [�[94mINFO�[0m] Waiting 5 seconds before retrying... [�[1m�[90mBfxWebsocket�[0m�[0m] [�[94mINFO�[0m] Reconnect attempt 1/5 [�[1m�[90mBfxWebsocket�[0m�[0m] [�[94mINFO�[0m] Websocket connected to wss://api-pub.bitfinex.com/ws/2 [�[1m�[90mBfxWebsocket�[0m�[0m] [�[94mINFO�[0m] {'event': 'info', 'version': 2, 'serverId': '028d5ea6-dbf1-49f2-9aed-605f72677161', 'platform': {'status': 1}} [�[1m�[90mBfxWebsocket�[0m�[0m] [�[94mINFO�[0m] Websocket opened. [�[1m�[90mBfxSubscriptionManager�[0m�[0m] [�[94mINFO�[0m] Subscribing to channel trades Exception in thread Thread-1: Traceback (most recent call last): File "C:\Users\Administrator\Desktop\Python\lib\threading.py", line 954, in _bootstrap_inner self.run() File "C:\Users\Administrator\Desktop\Python\lib\threading.py", line 892, in run self._target(*self._args, **self._kwargs) File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\generic_websocket.py", line 99, in start_loop loop.run_until_complete(self._run_socket()) File "C:\Users\Administrator\Desktop\Python\lib\asyncio\base_events.py", line 642, in run_until_complete return future.result() File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\generic_websocket.py", line 143, in _run_socket await self.on_message(sId, message) File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\bfx_websocket.py", line 472, in on_message await self._ws_system_handler(socketId, msg) File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\bfx_websocket.py", line 207, in _ws_system_handler await self._WS_SYSTEM_HANDLERS[eType](socketId, msg) File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\bfx_websocket.py", line 268, in _system_error_handler self._emit('error', err_string) File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\generic_websocket.py", line 193, in _emit self.events.emit(event, *args, **kwargs) File "C:\Users\Administrator\Desktop\Python\lib\site-packages\pyee\_base.py", line 116, in emit self._emit_handle_potential_error(event, args[0] if args else None) File "C:\Users\Administrator\Desktop\Python\lib\site-packages\pyee\_base.py", line 86, in _emit_handle_potential_error raise error TypeError: exceptions must derive from BaseException`

#### Steps to reproduce
```
 try:
            bfx = Client(API_KEY="",API_SECRET="")
            @bfx.ws.on('connected')
            async def start():
                await bfx.ws.subscribe('trades', 'tBTCUSD')

            trades = []

            @bfx.ws.on('new_trade')
            def new_trade(trade):

                global trades # -------------------------
                
                price = trade["price"]
                size = trade["amount"]

                if size > 0:
                    side = "buy"  
                else:
                    side = "sell"
                
                ticker = "BTCUSD"
                trades.append([ticker,side,round(price,1),size]) 

            bfx.ws.run()
            main()

 except Exception as e:
            traceback.print_exc()

```
##### Additional Notes:
I did not install it with pip since I get reccursion errors when I do with pip...I have folder bfx in files and import the folder...I doubt this would be the problem but posting here in case it might be

**Comment by slurpxbt** [comment]
any fixes on this ?

**Comment by itsdeka** [comment]
Thank you. I'll let it run to see what happens.
We have made several fixes in the last months, I hope you'll not have this issue after you upgrade.
Please also try to downgrade to python3.6 if just upgrading is not enough.

**Comment by itsdeka** [comment]
Did you also try to downgrade to 3.6?

**Comment by slurpxbt** [comment]
yes I also downgraded to 3.6

one more thing is it possible that this is happening beacue I run multiple
datastreams that I sent you...I run 3 files one for each ticker (btc, eth,
ethbtc)

V V pon., 10. maj 2021 ob 17:59 je oseba Dario Moceri <
***@***.***> napisala:
