### ISSUE TITLE
Order init has mistake

### ISSUE THREAD

**Issue by DmitriyG228** [bitfinexcom/bitfinex-api-py#138]
#### Issue type
- [ x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description

Once retrieving info with `bfx.rest.get_order_history` and in the event of amount being updated to reverse value (e.g. from 
-0.020578 to 0.033492) `amount_filled` gets wrong. After investigating the issue I have found out that `amount_filled` is not originally present in to API response, but calculated by `bitfinex-api-py` with `Order.__init__`, in particular with this piece of code

    `if self.amount_orig > 0:
            self.amount_filled = amount_orig - amount
        else:
            self.amount_filled = -(abs(amount_orig) - abs(amount))` 

This  returns wrong calcaulation for `amount_filled` in case order has been updated to reverse value. 

So, having  ` AMOUNT == 0.033492  and AMOUNT_ORIG == -0.020578  self.amount_filled = 0.012914 does not comply with bitfinex trades report, which is -0.054070. 

According to bitfinex support 'In the API response, we don't get the amount filled in the AMOUNT but rather get what's unfilled as the AMOUNT.' 

I am not bitfinex engine works right here, since why should updating amount from sell to buy should give sell? I have also enquired the support about that.

#### Steps to reproduce
-

**Comment by itsdeka** [comment]
Great, thank you very much @DmitriyG228  for reporting this

**Comment by itsdeka** [comment]
Hello @DmitriyG228,
please can you explain the steps you perform to get an order with a positive amount and a negative amount_orig?
How do you update the amount from sell to buy?

**Comment by DmitriyG228** [comment]
Hi, this happens when order amount is updated from negative to positive value or vice versa

**Comment by itsdeka** [comment]
Hi @DmitriyG228,
can you provide details about how you update the order amount from negative to positive? Do you use bitfinex-api-py, the web app or?

**Comment by DmitriyG228** [comment]
I am doing the entire thing through `bitfinex-api-py`. I think I could do a minimal reproducible example if I find time.

**Comment by itsdeka** [comment]
Yes, please. 
I can change the size of an order, even if it is already partially filled, but I get a DELTA ERROR if I try to flip an order from sell to buy or vice versa.

**Comment by DmitriyG228** [comment]
Hi, I have encountered the problem again. 

amount_orig = -0.00047
amount = 0.11503

ORDER_STATUS = 'POSTONLY CANCELED was: PARTIALLY FILLED @ 60321.0(-0.1155)'

but that amount_filled calculated is 0.11456

**Comment by DmitriyG228** [comment]
So, I seem to have found a mistake in the code. 

Right amount_filled is as simple as

`self.amount_filled = amount_orig - amount`
