### ISSUE TITLE
Support pip installation

### ISSUE THREAD

**Issue by redknightlois** [bitfinexcom/bitfinex-api-py#14]
The best way to package and distribute a python package is through pip. Currently, the API does not support that as it doesn't provide a `setup.py`
Packaging projects in python: https://packaging.python.org/tutorials/packaging-projects/

There are also other minor warnings like:
```
warning: the following paths have collided (e.g. case-sensitive paths on 
a case-insensitive filesystem) and only one from the same colliding group 
is in the working tree:

  'bfxapi/Client.py'
  'bfxapi/client.py'
  'bfxapi/models/Order.py'
  'bfxapi/models/order.py'
  'bfxapi/models/Position.py'
  'bfxapi/models/position.py'
  'bfxapi/models/Subscription.py'
  'bfxapi/models/subscription.py'
  'bfxapi/models/Trade.py'
  'bfxapi/models/trade.py'
  'bfxapi/models/Wallet.py'
  'bfxapi/models/wallet.py'
```

Repro:
- Execute `pip install git+https://github.com/bitfinexcom/bitfinex-api-py.git`

**Comment by gorillamania** [comment]
Can this be published to pypi?

**Comment by JacobPlaster** [comment]
Sure @gorillamania, done: https://pypi.org/project/bitfinex-api-py/
