### ISSUE TITLE
[Help/Exemple request] How to use the enable_flag on ws

### ISSUE THREAD

**Issue by PsykotropyK** [bitfinexcom/bitfinex-api-py#140]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request
- [x] exemple request

#### Brief description
Hello, my request is only on how to use the enable_flag. I would expect that after a subscription (for instance `bfx.ws.subscribe('book', 'tBTCUSD')`) I would get the Timestamp in the data received if I enable a flag with `bfx.ws.enable_flag(32768)`

As my coding knowledge is not high enough to understand alone how to actually receive the timestamp by reading the source code would you mind including an example of the enable_flag usage in the ws exemple and/or provide some guidance here?  

#### Steps to reproduce
based on  bfxapi\ws\subscribe_orderbook.py exemple, with the here under update:

```
async def start():
   await bfx.ws.subscribe('book', 'tBTCUSD')
   bfx.ws.enable_flag(32768)
```

**Comment by itsdeka** [comment]
Hello @PsykotropyK, I prepared an example

`import asyncio
import json
from bfxapi import Client
from bfxapi.websockets.bfx_websocket import Flags

bfx = Client(logLevel='DEBUG', API_KEY='', API_SECRET='',)

@bfx.ws.on('error')
def log_error(err):
  print ("Error: {}".format(err))

@bfx.ws.on('order_book_update')
def log_update(data):
  print ("Book update: {}".format(data))

@bfx.ws.on('order_book_snapshot')
def log_snapshot(data):
  print ("Initial book: {}".format(data))

async def start():
  await bfx.ws.enable_flag(Flags.TIMESTAMP)
  await bfx.ws.subscribe('book', 'tBTCUSD')

bfx.ws.on('connected', start)
bfx.ws.run()
`

This code will produces something like this in the console

```
[BfxWebsocket] [DEBUG] Heartbeat - wss://api-pub.staging.bitfinex.com/ws/2
[BfxWebsocket] [DEBUG] [1634,"hb",1621451347620]
```

The third (last) element of the array of the event 'heartbeat' is the timestamp

```
[BfxWebsocket] [DEBUG] [0,"wu",["margin","USTF0",1015.5231706,0,1015.5231706,null,null],1621451602670]
[BfxWebsocket] [INFO] Wallet update: Wallet <'margin_USTF0' balance='1015.5231706' balance_available='1015.5231706' unsettled='0'>
```

In this case too, the last element of the array of the event 'Wallet Update' is the timestamp

**Comment by itsdeka** [comment]
Hello @PsykotropyK, I prepared an example

```
import asyncio
import json
from bfxapi import Client
from bfxapi.websockets.bfx_websocket import Flags

bfx = Client(logLevel='DEBUG', API_KEY='', API_SECRET='',)

@bfx.ws.on('error')
def log_error(err):
  print ("Error: {}".format(err))

@bfx.ws.on('order_book_update')
def log_update(data):
  print ("Book update: {}".format(data))

@bfx.ws.on('order_book_snapshot')
def log_snapshot(data):
  print ("Initial book: {}".format(data))

async def start():
  await bfx.ws.enable_flag(Flags.TIMESTAMP)
  await bfx.ws.subscribe('book', 'tBTCUSD')

bfx.ws.on('connected', start)
bfx.ws.run()
```


This code will produces something like this in the console

```
[BfxWebsocket] [DEBUG] Heartbeat - wss://api-pub.bitfinex.com/ws/2
[BfxWebsocket] [DEBUG] [1634,"hb",1621451347620]
```

The third (last) element of the array of the event 'heartbeat' is the timestamp

```
[BfxWebsocket] [DEBUG] [0,"wu",["margin","USTF0",1015.5231706,0,1015.5231706,null,null],1621451602670]
[BfxWebsocket] [INFO] Wallet update: Wallet <'margin_USTF0' balance='1015.5231706' balance_available='1015.5231706' unsettled='0'>
```

In this case too, the last element of the array of the event 'Wallet Update' is the timestamp

**Comment by PsykotropyK** [comment]
Hello @itsdeka,

Thank you for the quick answer. 

So firstly I did not awaited the flag which I guess was why I did not see anything and then I expected it to be an additional info within the data that is subscribed and not only be part of the debug log. 

Anyway it allowed to better spot where should be the information and I now understand that the information is available within bfx_websocket.py in the `data`. In my case it would be `data[2]`, though in the values that are emitted only `data[0]` (actualy the symbol linked to `data[0]`) and `data[1]` are emitted to the event subscriptors. 

I played a bit with the flags and while `OB_CHECKSUM` is on by default, I see that I can't have both `TIMESTAMP` and `SEQ_ALL` as only the last one that is set will be visible in both DEBUG & `data` value. I checked it to see whether `data` will have the 'TIMESTAMP' at different index depending on the flags that are set. Given that one flag overrides the other, the additional information is necessarily at index 2 (`data[2]`)

If this is the expected results, shouldn't `data[2]` be emitted along the symbol and obInfo (`data[1]`), if it exists ?

Regards

**Comment by itsdeka** [comment]
Hello @PsykotropyK ,
you can sum flags to enable them at the same time.

`await bfx.ws.enable_flag(Flags.TIMESTAMP + Flags.SEQ_ALL)`

```
[BfxWebsocket] [DEBUG] [0,"wu",["funding","BTC",32.02674231,0,32.02674231,null,null],8,7,1621583835693]
[BfxWebsocket] [DEBUG] [0,"wu",["funding","ETH",10.00068131,0,10.00068131,null,null],9,7,1621583835693]
[BfxWebsocket] [DEBUG] [0,"wu",["funding","USD",10136.22483234,0,9836.22483234,null,null],10,7,1621583835693]
[BfxWebsocket] [DEBUG] [0,"wu",["exchange","BTC",0.897,0,0.897,null,null],11,7,1621583835693]
[BfxWebsocket] [DEBUG] [0,"wu",["exchange","USD",90959.8618,0,90959.8618,null,null],12,7,1621583835693]
```

**Comment by PsykotropyK** [comment]
Thanks @itsdeka 
Any way those informations would be emitted along the rest of the data in the different handlers of `bfx_websocket.py` ?
I find it easier to read it from the data received from the event subscription than from the logs. 
Maybe you'd like me to create a proper "new feature" request and close this one?

**Comment by itsdeka** [comment]
I am trying to understand if it makes sense to proceed with the requested implementation and if it has any side effect.
It would work as follows, is this what you would like to have?

```
async def _wallet_update_handler(self, data):
   uw = self.wallets._update_from_event(data)
   self._emit('wallet_update', uw, data)
   self.logger.info("Wallet update: {}".format(uw))
```

```
@bfx.ws.on('wallet_update')
def log_update(wallet, data):
  print(data) # with timestamp and other extra fields
  print ("Balance updates: {}".format(wallet))
```

**Comment by PsykotropyK** [comment]
I am not sure of what `data` contains in `_wallet_update_handler` as I was focused on `_order_book_handler` but I guess it is of similar structure, hence I'd say yes.

In `_order_book_handler` given that what is emitted is not actualy the data, it could be something like that:

    withFlags = (len(data) >= 3)
    if isSnapshot:
        self.orderBooks[symbol] = OrderBook()
        self.orderBooks[symbol].update_from_snapshot(obInfo, orig_raw_message)
        if withFlags:
            self._emit('order_book_snapshot', {
                   'symbol': symbol, 'data': obInfo, 'flags':data[2:len(data)-1]})
        else:
            self._emit('order_book_snapshot', {
                   'symbol': symbol, 'data': obInfo})

Though it may be easier to simply pass data, but that is not what is done at the moment

**Comment by itsdeka** [comment]
Thank you @PsykotropyK, It looks like this is a good request.
I'll work on it.

**Comment by itsdeka** [comment]
Hello @PsykotropyK, I have opened a PR here https://github.com/bitfinexcom/bitfinex-api-py/pull/147/files.
Please use it carefully, it still needs to be tested properly.

Could you also please close this discussion?

**Comment by PsykotropyK** [comment]
Ok I quickly read your code my understanding is that on top of the previous structure, you added the complete 'data' object. It seems great. I'll let you know if I find any conflicts.
