### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by s1737283** [bitfinexcom/bitfinex-api-py#142]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [x ] performance
- [ ] feature request

#### Brief description
The documentation for the REST endpoint that gets historical trades is misleading. It states that the start and end times must be strings. However, the API works if I input these as ints as well. Every other endpoint I have worked with states that these start and end times must be ints, so why does this endpoint require strings?
#### Steps to reproduce
-Make it clear which input must be used.

##### Additional Notes:
-

**Comment by itsdeka** [comment]
Hello @s1737283,
thanks for reporting this.
Could you link the exact point you think the documentation is wrong? I can't find it.

It is expected it works with both str and int values. As you can see, start and end parameters are used to build a URL.

```
endpoint = "auth/r/trades/{}/hist".format(symbol)        
params = "?start={}&amp;end={}&amp;limit={}".format(start, end, limit)
```

**Comment by itsdeka** [comment]
Hello @s1737283,
thanks for reporting this.

It is expected it works with both str and int values. As you can see, start and end parameters are used to build a URL.

```
endpoint = "auth/r/trades/{}/hist".format(symbol)        
params = "?start={}&amp;end={}&amp;limit={}".format(start, end, limit)
```

**Comment by s1737283** [comment]
Hi there, 

Thank you for getting back to me. It's just a bit misleading if the docs say it should be a string, but in all my personal experience I have been using ints, I didn't even realise that it was properly meant to be a string. It was just a suggestion that perhaps the labelling could be a bit more indicative and highlight that both could be used?
