### ISSUE TITLE
Account trade / trade update receiver not handling well

### ISSUE THREAD

**Issue by laikasinjason** [bitfinexcom/bitfinex-api-py#146]
#### Issue type
-  bug

#### Brief description
The trade (te) and trade update (tu) of user's account is not handling well.
It should already be subscribed and sent through chanId 0 ( so subscription should be checked )
More additional information can be received from account's trade, the parser is enriched.

#### Steps to reproduce
bfx.ws.on('new_trade', log_trade)
bfx.ws.on('trade_update', log_trade_update)

will not receive any event if the symbol is not subscribed but it should be handling trade from the user's account.
Moreover, there are account's information like the order id, fee, fee currency that can be received in those account's trades, it is not handling recently

##### Additional Notes:
I have made a fix on that but cannot push to the repository.

**Comment by itsdeka** [comment]
Hello Laika, could you please fork this repository (on the top right of the page), push there and open a pull request?
