### ISSUE TITLE
bfx.ws.stop: The future belongs to a different loop than the one specified as the loop argument

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#152]
#### Issue type

- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Motivation:

This is related to the discussion in the issue https://github.com/bitfinexcom/bitfinex-api-py/issues/141

I'd like to have a class BidAsk that will keep track of the latest bidask price. So far it seems that there is no other way than to keep track of the entire orderbook. Given this overhead I'd like something that can be stoped/started as needed. This comes handy with bots that only execute a trade on candle closes (say 4H bars) and, therefore, it would be wasteful to constantly pull orderbook data for such rare events.

 

#### Steps to reproduce
Bellow is the BidAsk class implementation. We see that upon trying to stop the WS connection an issue occurs

```
In [1]: import bidask
In [2]: B = bidask.BidAsk()
In [3]: B.last_price
Out[3]: 37213
In [4]: B.last_price
Out[4]: 37214
In [9]: await B.stop()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-792ddaf6df1e> in <module>
----> 1 await B.stop()

~/bidask.py in stop(self)
     14 
     15     async def stop(self):
---> 16         await self.bfx.ws.stop()
     17 
     18     async def start(self):

~/.local/lib/python3.9/site-packages/bitfinex_api_py-1.1.15-py3.9.egg/bfxapi/websockets/generic_websocket.py in stop(self)
    164         self.attempt_retry = False
    165         for key, socket in self.sockets.items():
--> 166             await socket.ws.close()
    167         self._emit('done')
    168 

~/.local/lib/python3.9/site-packages/websockets-8.1-py3.9-linux-x86_64.egg/websockets/protocol.py in close(self, code, reason)
    695             # If close() is canceled during the wait, self.transfer_data_task
    696             # is canceled before the timeout elapses.
--> 697             await asyncio.wait_for(
    698                 self.transfer_data_task,
    699                 self.close_timeout,

/usr/lib/python3.9/asyncio/tasks.py in wait_for(fut, timeout, loop)
    460     cb = functools.partial(_release_waiter, waiter)
    461 
--> 462     fut = ensure_future(fut, loop=loop)
    463     fut.add_done_callback(cb)
    464 

/usr/lib/python3.9/asyncio/tasks.py in ensure_future(coro_or_future, loop)
    671     elif futures.isfuture(coro_or_future):
    672         if loop is not None and loop is not futures._get_loop(coro_or_future):
--> 673             raise ValueError('The future belongs to a different loop than '
    674                              'the one specified as the loop argument')
    675         return coro_or_future

ValueError: The future belongs to a different loop than the one specified as the loop argument

```

What exactly is this issue? How can it be mitigated? I've been talking to some people on python IRC chanel and they said there is an issue with how the BFX API is designed. I am not an expert on this topic so I can't say what, but as I understood it, the WS constructor is spawning a thread or something.

Is there a way to fix this issue to achieve the desired result?

```
from bfxapi import Client
import asyncio

class BidAsk:
    def __init__(self):
        self.bfx = Client(logLevel='INFO')

        self.bfx.ws.on('connected', self.start)
        self.bfx.ws.on('order_book_update', self.log_update)
        self.bfx.ws.run()

    def log_update(self, data):
        self.last_price = data['data'][0]

    async def stop(self):
        await self.bfx.ws.stop()

    async def start(self):
        await self.bfx.ws.subscribe('book', 'tBTCUSD')
```
##### Additional Notes:
-
#151

**Comment by itsdeka** [comment]
Hello @jazarija, I am investigating about .stop(), my feeling is that with the new versions of asyncio it can't be used anymore.
In our case we are using asyncio to run an infinite loop, you will continue to receive WS messages forever. 
I think the cleanest way to approach this is to keep always online (when your bot is online) a ws process, and if you are worried about bandwidth/performance, unsubscribe from all channels when not needed. I would start from this example (https://github.com/bitfinexcom/bitfinex-api-py/blob/master/bfxapi/examples/ws/multiple_instances.py). Within Routine class there is a function do(), there you can define your logic. To store and retrieve the last price from your bot I would use Redis.
