### ISSUE TITLE
Receiving wrong price in "new_trade" callback when subscribing multiple trades

### ISSUE THREAD

**Issue by Jackdeve** [bitfinexcom/bitfinex-api-py#155]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
When i subscribe multiple symbols, most of the time i receive price of another symbol for a specific symbol inside the below callback function, for example the symbol is "tETHUSD" but the price for this symbol is BTC's price.
Is there any solution? 

@bfx.ws.on('new_trade')def log_trade(trade):  print ("New trade: {}".format(trade))

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by itsdeka** [comment]
Hello @Jackdeve, 
I can't reproduce this error on my end.

Can you please try with the following code and check if the problem persists?


```
import os
import sys
sys.path.append('../../../')

from bfxapi import Client

bfx = Client(
  logLevel='DEBUG'
)

@bfx.ws.on('error')
def log_error(err):
  print ("Error: {}".format(err))


@bfx.ws.on('new_trade')
def log_trade(trade):
  print ("New trade: {}".format(trade))

async def start():
  await bfx.ws.subscribe('trades', 'tBTCUSD')
  await bfx.ws.subscribe('trades', 'tETHUSD')
  await bfx.ws.subscribe('trades', 'tLTCUSD')

bfx.ws.on('connected', start)
bfx.ws.run()
```


Output

```
New trade: {'mts': 1624550252217, 'price': 1990.9, 'amount': 0.2, 'symbol': 'tETHUSD'}
New trade: {'mts': 1624550252503, 'price': 1991, 'amount': -0.38218063, 'symbol': 'tETHUSD'}
New trade: {'mts': 1624550253795, 'price': 33988, 'amount': 0.0002, 'symbol': 'tBTCUSD'}
```

**Comment by Jackdeve** [comment]
No error occurred this time, but i think if you let the program run for a while, it will occur. 
Anyway i could solve this using multiple clients for subscription.

**Comment by Jackdeve** [comment]
.
