### ISSUE TITLE
Looking for PRICE Response Field to show up in Active Orders

### ISSUE THREAD

**Issue by QuantumCrazy** [bitfinexcom/bitfinex-api-py#156]
#### Issue type
- [ ] bug
- [x] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
When checking active orders, how can we choose what response fields we want to show up? There is no "price" field that is returned for active orders, which for a trader is not very helpful. Bitfinex lists many response fields when submitting orders and one of them is "price" which I want returned in the output

https://docs.bitfinex.com/reference#rest-auth-submit-order

#### Steps to reproduce
Using the documentation in the REST API:

import os
import sys
import asyncio
import time
from bfxapi import Client, Order

bfx = Client(
  API_KEY='API_KEY',
  API_SECRET='API_SECRET'
)

async def log_active_orders():
  orders = await bfx.rest.get_active_orders('tBTCUSD')
  print ("Orders:")
  [ print (o) for o in orders ]

async def run():
 await log_active_orders()

t = asyncio.ensure_future(run())
asyncio.get_event_loop().run_until_complete(t)

##### Additional Notes:
This is my first time connecting to an API

The output to the code above I get is the following:

Orders:
Order <'tBTCUSD' amount_orig=XXXX amount_filled=-0.0 mts_create=XXXXXXXXXXXX status='ACTIVE' id=XXXXXXXXXX>

As you can see, there are only a handful of response fields showing. How can we pick which fields we want returned and in particular, "price" to show up, so I can see at what prices my orders stand.

Thanks

**Comment by itsdeka** [comment]
Hello @QuantumCrazy,
you can change your log_active_orders function with

```
async def log_active_orders():
    orders = await bfx.rest.get_active_orders('tBTCUSD')
    print ("Orders:")
    for order in orders:
        print(f"{order.symbol} | id={order.id} status={order.status} "
              f"amount_orig={order.amount_orig} amount_filled={order.amount_filled} price={order.price} price_avg={order.price_avg}")
```

You can find all the fields here -> https://github.com/bitfinexcom/bitfinex-api-py/blob/master/bfxapi/models/order.py#L114

**Comment by QuantumCrazy** [comment]
Thanks!
