### ISSUE TITLE
Market Orders - Best Practices

### ISSUE THREAD

**Issue by QuantumCrazy** [bitfinexcom/bitfinex-api-py#164]
I'm building an AI algo system that will need to execute trades with the API and I'm looking for a guarantee of trade execution above a price guarantee. The problem is every time I put through a market order it generally fails. Due to price fluctuations, the price field I enter is the last price from the public ticker. Is there a functionality that I am missing - what is the best way to guarantee a market order execution, especially relating to the price we enter for such an order?

**Comment by itsdeka** [comment]
Hello @QuantumCrazy,
it is not possible to guarantee a market order execution.

I prepared a few snippets you can use to build a custom logic within your bot to estimate the effect of a market sell.

```
def split_bids_and_asks(book):
    last_value = 0
    bids = []
    asks = []
    for i in range(0, len(book)):
        if not last_value or book[i][0] < last_value:
            last_value = book[i][0]
            bids.append(book[i])
        else:
            asks.append(book[i])
    return bids, asks
    
def get_available_bids_liquidity(bids, min_price):
    # example bid -> [price, count, amount]
    amount = 0
    for bid in bids:
        if bid[0] > min_price:
            amount += bid[2]
    return amount


def get_available_asks_liquidity(asks, min_price):
    # example ask -> [price, count, amount]
    amount = 0
    for ask in asks:
        if ask[0] < min_price:
            amount += ask[2] * -1
    return amount


def simulate_sell(bids, amount, fee=0.002):
    # example bid -> [price, count, amount]
    obtained = 0
    for bid in bids:
        if bid[2] > amount:
            obtained += amount * bid[0]
            break
        else:
            obtained += bid[2] * bid[0]
            amount -= bid[2]
    return obtained * 1 - fee

book = await bfx.rest.get_public_books(f"tBTCUSD", precision="P0", length=25)
bids, asks = split_bids_and_asks(book)
bfx_obtainable = simulate_sell(bids, 1000)
print(f"BFX Obtainable: {bfx_obtainable} - Spent: {spent}")
```

**Comment by QuantumCrazy** [comment]
Thanks, I appreciate you taking the time to put this together. That should get me on the right track.

**Comment by QuantumCrazy** [comment]
Hi @itsdeka, just a quick one on your snippets.....when I arranged the logic I'm getting an error

`NameError: name 'spent' is not defined`

I don't think you defined `spent` in your code?

**Comment by itsdeka** [comment]
Hello @QuantumCrazy,
`spent` is the amount of USD used to buy that 1000 BTC and `bfx_obtainable` is the amount of USD you can get market selling that 1000 BTC on BFX. It is not defined in my snippets.

`count` is the number of orders which constitutes that amount at that price, if 4 different users are buying 0.1 BTC at 10.000 USD, the line will be 10000, 4, 0.4.

**Comment by QuantumCrazy** [comment]
Thanks
