### ISSUE TITLE
Wrong endpoint for public tickers

### ISSUE THREAD

**Issue by pablomerix** [bitfinexcom/bitfinex-api-py#165]
https://github.com/bitfinexcom/bitfinex-api-py/blob/62501edfa0cee70d688bd16aedafd1def8e28e40/bfxapi/rest/bfx_rest.py#L177

From you API documentation I can see that this endpoint url should look like this:
```
https://api-pub.bitfinex.com/v2/tickers?symbols=tBTCUSD,tLTCUSD,fUS
```
Instead of the format it has on the library, which is:
```
 endpoint = "tickers/?symbols={}".format(','.join(symbols))
 ```
 You need to remove the `/` before `?symbols`

**Comment by itsdeka** [comment]
Hello @pablomerix, thank you very much for reporting this.
It looks like that both versions work, but I agree it is better to be consistent.

[With /](https://api-pub.bitfinex.com/v2/tickers/?symbols=tBTCUSD,tLTCUSD)
[Without /](https://api-pub.bitfinex.com/v2/tickers?symbols=tBTCUSD,tLTCUSD)
