### ISSUE TITLE
Error 10001 Invalid order: not enough exchange balance ERROR for SUBMITTING ORDER ETHBTC

### ISSUE THREAD

**Issue by QuantumCrazy** [bitfinexcom/bitfinex-api-py#168]
Hi, some snippets of my error. My BTC trades normally perform fine but today I was trading ETH for BTC and my ETH balance was definitely topped up so I have no idea why this error in submitting the order came up. 
```
response = await bfx.rest.submit_order(
raw_notification = await self.post(endpoint, payload)
raise Exception('POST {} failed with status {} - {}'
Exception: POST failed with status 500 - ["error",10001,"Invalid order: not enough exchange balance for XXX ETHBTC at YYY
```
XXX was the exchange balance amount which was actually less than the full available ETH wallet balance and YYY was the ETHBTC ask price. I am using the REST V2 API and submitting through an Exchange FOK order.

Any help appreciated, thanks!

P.S - apologies.....my error here - **forgot to specify a negative sign for the quantity in a sell order**

**Comment by peterlee909** [comment]
I got the same error.
I got enough exchange but can not submit the order correctly.
Anyone can help me?

P.S. I can submit the order correctly on the app with same parameters.

**Comment by QuantumCrazy** [comment]
@peterlee909 I fixed my error with the negative sign, your error is most likely a syntax error in your code

**Comment by peterlee909** [comment]
@QuantumCrazy Thank you. I have solved it. The order type I wanted to submit is EXCHANGE_LIMIT, and I did not give the correct parameters.
