### ISSUE TITLE
API does not support Market orders.

### ISSUE THREAD

**Issue by pycoder2014** [bitfinexcom/bitfinex-api-py#171]
#### Issue type
- [ ] bug
- [x ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Neither the Rest nor Websocket api supports Market orders. That's not very nice. Is there a technical reason for this?

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by pycoder2014** [comment]
Hi Dario,
If you take a closer look at the signature of that submit_order function, you'll see that it takes price as a positional argument therefore its required.

https://github.com/bitfinexcom/bitfinex-api-py/blob/a7eade4cdabde03073bb49946190c3b5668ca0ac/bfxapi/rest/bfx_rest.py#L735

**Comment by itsdeka** [comment]
Oh, I am sorry.
You are right. I am opening a PR to fix it. 
Of course, you can just pass price=None to use it with the already published version of this library.

```
from bfxapi.models.order import OrderType
response = await bfx.rest.submit_order(symbol="tBTCUSD", amount=0.1, price=None, market_type=OrderType.MARKET)
```

**Comment by itsdeka** [comment]
https://github.com/bitfinexcom/bitfinex-api-py/pull/174

**Comment by itsdeka** [comment]
https://github.com/bitfinexcom/bitfinex-api-py/pull/175

**Comment by vigan-abd** [comment]
hi @itsdeka @pycoder2014 
merged example usage for market order (https://github.com/bitfinexcom/bitfinex-api-py/pull/175), closing the issue
