### ISSUE TITLE
`get_order_history` not handling `ids` when specified

### ISSUE THREAD

**Issue by krisuj** [bitfinexcom/bitfinex-api-py#172]
#### Issue type
- [x ] bug
- [ x] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I am trying to check the status of a specific set of orders, for which I have saved the order `ids`

I am trying to use `get_order_history` REST call specifying `ids` field, but the call returns an empty result set. 

When I make the call without the ids, the returned list of orders (all cancelled orders) have the previously specified ids in there; so something seems off here.

#### Steps to reproduce
- Call `get_order_history` without specifying `ids` argument
- Save the order_ids from the above result set
- Call `get_order_history` specifying `ids` argument, with a subset of the earlier returned results
- This will be an empty set

##### Additional Notes:
- As an enhancement, it will be so useful to be able to retrieve a set of orders based on `ids`, in a single call; whether they are active or inactive (cancelled or executed). Right now you have to use two endpoints `get_active_orders` and `get_order_history`, which both seem to not handle `ids` correctly

**Comment by itsdeka** [comment]
Hello @krisuj, thanks for reporting this issue.
I have pushed a PR (https://github.com/bitfinexcom/bitfinex-api-py/pull/177), it will be merged as soon as possible.
