### ISSUE TITLE
ws_capacity not workingx

### ISSUE THREAD

**Issue by Bwahharharrr** [bitfinexcom/bitfinex-api-py#176]
#### Issue type
- [ x] bug

#### Brief description
ws_capacity not working

#### Steps to reproduce
- git pull
- example code to test:
```python
import os
import sys
from bfxapi import Client, Order

bfx = Client(ws_capacity=3)

tickers = ['tBTCUSD','tETHUSD','tSOLUSD','tLTCUSD']

@bfx.ws.on('connected')
async def blah():
    for t in tickers:
        await bfx.ws.subscribe_trades(t)


@bfx.ws.on('new_trade')
def log_trade(trade):
  #print ("New trade: {}".format(trade))
  pass

bfx.ws.run()
```

Fails:
`RuntimeError: cannot schedule new futures after interpreter shutdown`

Ref:
https://github.com/bitfinexcom/bitfinex-api-py/pull/22/commits/13e7d505f8ba85e0dfc00ac1ae1c8c1b005b2563
@JacobPlaster

could also be relevant, upgrading websockets from 8.1 to 10.0
https://github.com/bitfinexcom/bitfinex-api-py/pull/154

**Comment by Bwahharharrr** [comment]
Can you confirm @itsdeka  ?

**Comment by itsdeka** [comment]
Hello @Bwahharharrr, sorry for the late reply.
I have tried to run your code with websockets 10.0, 9.1 and 8.1 and I have never seen the error described.
Which version of Python are you using? All the other dependencies are as specified in requirementx.txt?

**Comment by Bwahharharrr** [comment]
Hi @itsdeka - python version 3.9.2, i just reproduced the test again on an entirely new virtual machine, you can see the log here:
https://asciinema.org/a/LXh9tL4Fgo1z8G26GfLQlocuw

**Comment by itsdeka** [comment]
Thanks for the video. 
Using 3.9.2 I can reproduce it. Please, consider the possibility of downgrading to 3.8 where this issue does not exist.
I'll try to find a solution.

**Comment by Bwahharharrr** [comment]
Keen to upgrade rather than downgrade;
I just tested on 3.9.9, same issue/error.

- Can confirm it does work on 3.8.0

**Comment by itsdeka** [comment]
@Bwahharharrr hello, I found a solution to support Py > 3.9.
Please I'd appreciate if you could confirm that everything works as expected on your end with these changes (https://github.com/bitfinexcom/bitfinex-api-py/pull/180).

**Comment by Bwahharharrr** [comment]
@itsdeka I have run the marketorders from your repo with the asyncio_nest code in, which having used before, I thought, 'yes, this will work running this new even loop inside the existing one', however. The code failed to execute properly, and here is why:

The example code above, attempts to subscribe to 4 tickets, opening up 2 websockets.
Now, the 2nd websocket connection is at least opening, which is an improvement. HOWEVER.. It never subscribes to the channels.

See here.
![[image](https://imgur.com/a/rt2oHvv)](https://i.imgur.com/lpWsN0M.png)

```python
import os
import sys
from bfxapi import Client, Order

bfx = Client(ws_capacity=3)

tickers = ['tBTCUSD','tETHUSD','tSOLUSD','tLTCUSD']

@bfx.ws.on('connected')
async def blah():
    for t in tickers:
        await bfx.ws.subscribe_trades(t)

@bfx.ws.on('subscribed')
async def subscribed(data):
    print(f"Subscribed to {data.channel_name}, {data.symbol}")

@bfx.ws.on('new_trade')
def log_trade(trade):
    print ("New trade: {}".format(trade))

bfx.ws.run()

```

**Comment by itsdeka** [comment]
Great, thanks for your feedback.
I am on it.

**Comment by itsdeka** [comment]
@Bwahharharrr I removed nest_asyncio and found another way.
Can you please give a look? Your example looks good on my end.

https://github.com/bitfinexcom/bitfinex-api-py/pull/180/files

**Comment by Bwahharharrr** [comment]
@itsdeka Run on my system and the test did indeed subscribe to the 4 tickers opening up 2 separate channels, so that much looks good.
I'll update my end in the next few days and continue using and report back any further related issues but so far looks like good job
