### ISSUE TITLE
How to get funding earnings?

### ISSUE THREAD

**Issue by peterlee909** [bitfinexcom/bitfinex-api-py#178]
#### Issue type
- [ ] bug
- [X] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
How to get funding earnings?

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by itsdeka** [comment]
Hello peterlee, you can find the available endpoints here
https://docs.bitfinex.com/reference#rest-auth-info-funding

**Comment by peterlee909** [comment]
Hello @itsdeka. Thanks for your reply.
I found that is a websocket api and there is no Rest api to get funding info?

**Comment by peterlee909** [comment]
The really thing I want to get is the Funding Earnings in the Report page.
I could not get the reference in the given link.
Is there any way to get the information I want?
Thanks.

**Comment by xiandong79** [comment]
I have the same question
