### ISSUE TITLE
Data not matching (BTCUSD)

### ISSUE THREAD

**Issue by mehdijoe** [bitfinexcom/bitfinex-api-py#181]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I dont know if it is a bug, my mistake or should it be a feature request. I am new to this and i couldnt pinpoint the issue. But I see huge discrepancies between crypto price obtaind from api_v2.candles and prices in other brokers. For example, on 2021/12/04 @06:00 BTCUSDT dropped to $42000, other brokers also showed the same drop (but binance was slightly bigger, I think it can be due to amount of bots which makes changes more exaggerated) but the "low"price obtained by the API was far from this. Not even many hours after and before that the price went below $47000. I know my time is UTC+1, so i scoped a bit data from API after and before 6:00 as it can be seen below
low | Date
-- | --
55162 | 2021-12-03 18:00
54913 | 2021-12-03 19:00
54067 | 2021-12-03 20:00
54065.02 | 2021-12-03 21:00
53746 | 2021-12-03 22:00
53872 | 2021-12-03 23:00
53879 | 2021-12-04 0:00
53222.97 | 2021-12-04 1:00
53149 | 2021-12-04 2:00
53150 | 2021-12-04 3:00
52640 | 2021-12-04 4:00
50758 | 2021-12-04 5:00
49187 | 2021-12-04 6:00
47628 | 2021-12-04 7:00
47963 | 2021-12-04 8:00
47750 | 2021-12-04 9:00
47667 | 2021-12-04 10:00
47482 | 2021-12-04 11:00
47619 | 2021-12-04 12:00
47504.97 | 2021-12-04 13:00
47904 | 2021-12-04 14:00
48595.78 | 2021-12-04 15:00
48551 | 2021-12-04 16:00
48420 | 2021-12-04 17:00
48933 | 2021-12-04 18:00
49500 | 2021-12-04 19:00
49529 | 2021-12-04 20:00
49416 | 2021-12-04 21:00
49369 | 2021-12-04 22:00
49538 | 2021-12-04 23:00

My question is, why is so? or am i doing a stupid mistake? from which broker does this data come from? and is there an option to specify the timezone so the shifting of date is down automatically?

</body>

</html>

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by itsdeka** [comment]
Hello @mehdijoe,
try to compare the prices you get from the APIs to the ones you see on the chart.
Do they match?

The data you get calling _Candles_ endpoint comes from Bitfinex.
In the response you receive a field called _MTS_ which is the millisecond timestamp.

You can create an additional field _date_ with the timezone you are interested in with something like

```
from datetime import datetime
import pytz
dt = datetime.fromtimestamp(MTS/1000)
pacific_tzinfo = pytz.timezone("US/Pacific")
pacific_dt = default_time.astimezone(pacific_tzinfo)
```

More details
[https://www.kite.com/python/answers/how-to-convert-timezones-in-python](https://www.kite.com/python/answers/how-to-convert-timezones-in-python)

**Comment by NotoriousPyro** [comment]
I ended up doing it like this, because it doesn't require pytz. For some reason the MTS number has three extra zeroes after the timestamp so I just append 000 to the timestamp...

```python
start_date = (int(datetime.fromisoformat("2023-08-17 22:00:00.000000").timestamp()))
stop_date = (int(datetime.fromisoformat("2023-08-17 23:00:00.000000").timestamp()))

candles = bfx.rest.public.get_candles_hist(tf='1m', symbol='tBTCUSD', end=f"{stop_date}000")
```

**Comment by NotoriousPyro** [comment]
I think that `start`, `end`, and any parameter that requires formatting into an MTS number should be `datetime` and not `str` as parameter types.

It's confusing to have to figure this out from calling the endpoint with a timestamp number, only to find out it was missing 3 zeroes...

**Comment by mehdijoe** [comment]
You dumb!!

Med vänlig hälsning / Best regards,
Mehdi Javdani
