### ISSUE TITLE
Rest API missing Liquidations implementation

### ISSUE THREAD

**Issue by jorxster** [bitfinexcom/bitfinex-api-py#202]
#### Issue type
- [ ] bug
- [ X] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
There's no function call for the Liquidations REST endpoint.
https://docs.bitfinex.com/reference/rest-public-liquidations

I'm happy to implement this, but **_IS this repository still maintained?_**? No merges for months... Seems like maintainer has ditched it? Please correct me if I'm wrong.

**Comment by itsdeka** [comment]
Released
