### ISSUE TITLE
bitfinex-api-py/bfxapi/rest/ public stats data

### ISSUE THREAD

**Issue by YZhao-BlockFi** [bitfinexcom/bitfinex-api-py#210]
Hello, 

I'm using Bitfinex API to pull some volume 1d/7d/30d data showing in this webpage: https://www.bitfinex.com/stats/#volume. I'm referring to the following code/doc to create my function:

https://github.com/bitfinexcom/bitfinex-api-py/blob/master/bfxapi/rest/bfx_rest.py
https://docs.bitfinex.com/reference/rest-public-stats1

async def log_public_stats():
  status = await bfx.rest.get_public_stats("vol.1d", "30m", 'fUSD', "hist", "long")
  print ("Public Stats:")
  print (status)

No matter what I put in key, size, symbol,... parameters, I can't get any data. Can someone help me on this? Thank you!

Best,
y

**Comment by itsdeka** [comment]
To get the volume I suggest to directly query

[](https://api-pub.bitfinex.com/v2/stats1/vol.1d:30m:BFX/hist)
