### ISSUE TITLE
Not working with python3.10 asyncio

### ISSUE THREAD

**Issue by jackpap** [bitfinexcom/bitfinex-api-py#213]
#### Issue type
- [x] bug

#### Brief description
Example doesn't work with python > 3.10

#### Steps to reproduce
Any of the examples will generate the following : 

File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

**Comment by itsdeka** [comment]
Thank you @jackpap, we are aware and have solved this issue.
We'll release soon the new version of bitfinex-api-py with major upgrades and fixes.

**Comment by cyclux** [comment]
Same issue here. Is there maybe an update on when the release of new version is scheduled?
