### ISSUE TITLE
Unknown data event: '[0.79816, 0, 1]' [54, [0.79816, 0, 1]]

### ISSUE THREAD

**Issue by alexanderborsch** [bitfinexcom/bitfinex-api-py#214]
#### Issue type
- [*] bug
- [ ] missing functionality
- [*] performance
- [ ] feature request

#### Brief description
Getting this sort of errors from time to time:
`[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79816, 0, 1]' [54, [0.79816, 0, 1]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79756, 0, 1]' [54, [0.79756, 0, 1]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79895, 0, -1]' [54, [0.79895, 0, -1]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79972, 0, -1]' [54, [0.79972, 0, -1]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79823, 1, 222]' [54, [0.79823, 1, 222]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79811, 1, 1252.9]' [54, [0.79811, 1, 1252.9]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79905, 1, -500.5]' [54, [0.79905, 1, -500.5]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79946, 2, -3807.78846653]' [54, [0.79946, 2, -3807.78846653]]
[ESC[1mESC[90mBfxWebsocketESC[0mESC[0m] [ESC[93mWARNINGESC[0m] Unknown data event: '[0.79978, 1, -199.90985246]' [54, [0.79978, 1, -199.90985246]]
`
#### Steps to reproduce
-

##### Additional Notes:
-
There is no way to see if a client fails to process order book data updates, checksum thing doesn't seem to do anything. Please make this warnings pushed up as notifications.

**Comment by itsdeka** [comment]
Thank you for the suggestion, I'll make sure we consider this for the next update
