### ISSUE TITLE
Failing "import bfxapi"

### ISSUE THREAD

**Issue by alsxz-bit** [bitfinexcom/bitfinex-api-py#229]
Fail to run this python code:

```
import bfxapi
print("THEEND")
```

It never prints "THEEND" out. Just ends execution somewhere in the "import" without any notes. I run it under Windows. 
Here is additional info:

>py --version
Python 3.12.0 

>py -m pip show bitfinex-api-py
Name: bitfinex-api-py
Version: 3.0.0b1
Summary: Official Bitfinex Python API
Home-page: https://github.com/bitfinexcom/bitfinex-api-py                                                                                                                          Author: Bitfinex
Author-email: support@bitfinex.com                                                                                                                                                 License: Apache-2.0
Location: C:\xxxxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages                                                                                                 Requires: pyee, requests, websockets                                                                                                                                               Required-by:

Modules pyee, requests, websockets, urllib3 are installed.

Where can I look to find the solution ? Thanks.

**Comment by kaibr** [comment]
Similar issue here with 3.0.0.b5 on Linux, Python 3.12.2. 

Just importing bfxapi segfaults. 

Fixed by downgrading to Python 3.11.8.
