### ISSUE TITLE
Withdrawal endpoint

### ISSUE THREAD

**Issue by LeonidVV** [bitfinexcom/bitfinex-api-py#23]
Hi.

I can not find the implementation of withdrawal rest endpoint for v1 or equivalent for v2.
Will these methods be implemented in the future?
If the method exists, show the sample code please.

**Comment by JacobPlaster** [comment]
Hey @LeonidVV, currently this library only implements the v2 endpoints and since the v2/withdraw endpoint is in active development it isnt available yet.

**Comment by LeonidVV** [comment]
Hey JacobPlaster.
Will withdrawal endpoint be implemented  in the near future?
Is there any other way to use withdrawal except ui?

**Comment by JacobPlaster** [comment]
@LeonidVV we will be releasing the v2 endpoint for withdraw very soon (its currently being tested in our staging environment).

> Is there any other way to use withdrawal except ui?
You would have to implement it using the v1 endpoint yourself: https://docs.bitfinex.com/reference#rest-auth-withdrawal

**Comment by JacobPlaster** [comment]
This is available now using the function `submit_wallet_withdraw`
