### ISSUE TITLE
How to post a SELL order via ws?

### ISSUE THREAD

**Issue by mprestonise** [bitfinexcom/bitfinex-api-py#29]
#### Issue type
Missing functionality

#### Brief description
I am trying to place a "SELL" order, but it's not working

#### Steps to reproduce
- Using the Order model, via WS, create an order like: `await bfx.ws.submit_order('tBTCUSD', 10944, 0.01, Order.Side.SELL)`
- Log out the order in async def trade_completed(order):
- It's placed a buy order

**Comment by lucasege** [comment]
You simply need to provide a negative value for `amount`:
Excerpt from `bitfinex-api-py/bfxapi/websockets/order_manager.py:89`
```
async def submit_order(self, symbol, price, amount, market_type=Order.Type.LIMIT,
                           hidden=False, price_trailing=None, price_aux_limit=None,
                           oco_stop_price=None, close=False, reduce_only=False,
                           post_only=False, oco=False, time_in_force=None,
                           onConfirm=None, onClose=None, gid=None, *args, **kwargs):
        """
        Submit a new order
        @param gid: assign the order to a group identitfier
        @param symbol: the name of the symbol i.e 'tBTCUSD
        @param price: the price you want to buy/sell at (must be positive)
        @param amount: order size: how much you want to buy/sell,
          a negative amount indicates a sell order and positive a buy order
        @param market_type	Order.Type: please see Order.Type enum
          amount	decimal string	Positive for buy, Negative for sell
```
Also, the fourth parameter is `market_type` as in the type of the order: market, limit, Immediate-or-Cancel, etc. These are enumerated in `bitfinex-api-py/bfxapi/models/order.py`.

So for your example this is what you're looking for: `await bfx.ws.submit_order('tBTCUSD', 10944, -0.01, Order.Type.EXCHANGE_MARKET)`. 

Tested with my account and it works just fine, I would suggest closing the issue, unless this does not address it sufficiently. Let me know.

**Comment by mprestonise** [comment]
Thanks @lucasege, this is missing from the documentation.
