### ISSUE TITLE
order not working properly

### ISSUE THREAD

**Issue by xyzjust** [bitfinexcom/bitfinex-api-py#31]
#### Issue type
- [x] bug
- [x] missing functionality
- [x] performance
- [ ] feature request

#### Brief description
I submitted an order to test, I put an order for 12 XPR at 0.22, but somehow it executed at 0.25462 (see first and last line of attached). 

Any idea on how to fix it? 

Also, how do I sell? I can't find an example how how to place a sell order

##### Additional Notes:
![image](https://user-images.githubusercontent.com/36056509/64068840-d3c8dc80-cc35-11e9-81eb-48f9be56cef7.png)

**Comment by JacobPlaster** [comment]
That definitely looks like a bug, ill test this out. Do you have any code samples to help reproduce???

Also I notice that you have closed the issue, was it a mistake?
