### ISSUE TITLE
Candle snapshot event

### ISSUE THREAD

**Issue by jbm1991** [bitfinexcom/bitfinex-api-py#33]
#### Issue type
- [ ] bug
- [X] missing functionality
- [ ] performance
- [X] feature request

#### Brief description
I see that snapshot events are available for other types such as Orders, Wallets, etc. but there is no such event for Candles. Is there any plan to add that as an event, or am I missing something obvious?

#### Steps to reproduce
- NA

##### Additional Notes:
- NA

**Comment by JacobPlaster** [comment]
Good idea @jbm1991, we can add that to our TODOs or feel free to open PR
