### ISSUE TITLE
Tickers events and snapshots

### ISSUE THREAD

**Issue by mariolinovIC** [bitfinexcom/bitfinex-api-py#37]
Hi,

I have seen that it is possible to subscribe to tickers, but I cannot see in the documentation the event names for new tickers and to get a initial snapshot. Are these events already implemented?

Thanks

**Comment by ph4z** [comment]
It is implemented and [documented](https://github.com/bitfinexcom/bitfinex-api-py/blob/master/docs/ws_v2.md#subscribe_ticker).
