### ISSUE TITLE
from_raw_order not found error

### ISSUE THREAD

**Issue by jonatan-klock** [bitfinexcom/bitfinex-api-py#47]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I'm have installed the latest package version bitfinex-api-py (1.1.3). Run the rest example in: bitfinex-api-py/bfxapi/examples/rest/create_order.py / 
Get error: from_raw_order not found error

#### Steps to reproduce
-run the example: bitfinex-api-py/bfxapi/examples/rest/create_order.py / 

##### Additional Notes:
- seemed to have been fixed in code modification #43, not still not  working

**Comment by JacobPlaster** [comment]
Hi @jonatan-klock, thanks for reporting the issue.

This issue has already been fixed (commit https://github.com/bitfinexcom/bitfinex-api-py/commit/7db6b5d73fd95ff7330d27c842c39d0141e04dd1) so please upgrade to 1.1.4

**Comment by jonatan-klock** [comment]
hi @JacobPlaster, yes I know, When I uninstalled the package and reinstalled it using pip install bitfinex-api-py I got version 1.1.3 as default, I suppose I need to specify explicit version 1.1.4. Thanks for your quick response much appreciated. Why does pip install 1.1.3 as default?

**Comment by JacobPlaster** [comment]
I see, thanks for pointing that out. Ill update pip to 1.1.4 now
