### ISSUE TITLE
rest, submit_order, error "Notification' has no attribute 'from_raw_order"

### ISSUE THREAD

**Issue by Mnogoidey** [bitfinexcom/bitfinex-api-py#49]
Trying to put new order , get an error below:
...bfxapi\rest\bfx_rest.py", line 546, in submit_order
AttributeError: type object 'Notification' has no attribute 'from_raw_order'

Unfortunately, I'm not enough experience to understand what the problem is.
I will be grateful for the help.

My code:
async def bf_rest_stream():
    bfx_rest = Client(
        API_KEY='',
        API_SECRET=''
    )
    time.sleep(2)

    while True:
            for key in copy_start_orders:

                up_order = copy_start_orders[key]
                
                if up_order.eid is False:
                    print('Sending new order from BF WS: ' + str(up_order))
                    response = await bfx_rest.rest.submit_order(pair, up_order.price, up_order.quantity,
                                                           up_order.order_type, up_order.hidden,
                                                           gid=up_order.gid)
                    for o in response.notify_info:
                        print("Order: ", o)
                
            start_orders.clear()
        time.sleep(1)

**Comment by JacobPlaster** [comment]
Hey @Mnogoidey, thanks for reporting the issue. We have actually fixed this one (pr https://github.com/bitfinexcom/bitfinex-api-py/pull/43) so please make sure youre using the latest version `1.1.4`
