### ISSUE TITLE
get_public_trades stalls forever

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#51]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I think I might be having a misunderstanding of how asyncio is supposed to work and/or how this API is designed. Consider the following (striped down) example from the codebase

```
import os, sys, asyncio, time
sys.path.append('../')

from bfxapi import Client

bfx = Client(logLevel='DEBUG')

now = int(round(time.time() * 1000))
then = now - 10000 

async def log_historical_trades():
  trades = await bfx.rest.get_public_trades('tBTCUSD', start=then, end=now, limit=10000)
  [ print (t) for t in trades ]

async def run():
   await log_historical_trades()
t = asyncio.ensure_future(run())
asyncio.get_event_loop().run_until_complete(t)


```
#### Steps to reproduce
-
The above program is supposed to print the trades happening in the last 10k millisecond. Indeed, it does that, but then blocks forever. 

What exactly am I missing here? How can one stop the execution and continue fetching new trades?

##### Additional Notes:
-

**Comment by JacobPlaster** [comment]
The program blocks because of the async thread in the background, try this:

```
import os, sys, asyncio, time
sys.path.append('../')

from bfxapi import Client

bfx = Client(logLevel='DEBUG')

now = int(round(time.time() * 1000))
then = now - 10000 

async def log_historical_trades():
  trades = await bfx.rest.get_public_trades('tBTCUSD', start=then, end=now, limit=10000)
  [ print (t) for t in trades ]

async def run():
    while true:
        await log_historical_trades()
        await asyncio.sleep(2)
t = asyncio.ensure_future(run())
asyncio.get_event_loop().run_until_complete(t)
```
