### ISSUE TITLE
[BfxWebsocket] [ERROR] Notification ERROR: price_aux_limit: invalid

### ISSUE THREAD

**Issue by therealirrationalcoder** [bitfinexcom/bitfinex-api-py#54]
#### Issue type
- [ ] bug
- [x] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I am attempting to use the bfx.ws.submit_order function to place an order.
It appears that it is impossible to place an exchange stop limit buy order. No matter what value is provided for the price_aux_limit parameter the API returns the error:

[BfxWebsocket] [ERROR] Notification ERROR: price_aux_limit: invalid

I tried a decimal value greater than the price, equal to the price, less than the price, a very small value (assuming it might be a delta to the price) and even None as well as a negative value.
 
Please add a possibility to submit exchange stop limit buy order via the python api.

#### Steps to reproduce
call: 

bfx.ws.submit_order(symbol='tBTCUSD', price=8500.5, price_aux_limit=8501.5, amount=0.001, market_type=Order.Type.EXCHANGE_STOP_LIMIT)) 

from a successfully authenticated websocket client.

##### Additional Notes:
- I am having great difficulty infering the correct call signatures for any type of order from the provided API documentation. Example code for each type of allowed order would be extremely helpful.

**Comment by JacobPlaster** [comment]
Hist @therealirrationalcoder its seems that you are submitting incorrect values. The price_aux_limit has to be below the current ticker price when buy and above when selling. For example:

```
bfx.ws.submit_order(symbol='tBTCUSD', price=8500.5, price_aux_limit=5001.5, amount=0.001, market_type=Order.Type.EXCHANGE_STOP_LIMIT))
```

OCO orders can get a little confusing so I like to use the webUI just to test it out a little before I code it, that way you will get a more descriptive error response for submitting invalid params.
