### ISSUE TITLE
ws.submit_order returning none

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#57]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ x] feature request

#### Brief description

Suppose I want to market buy BTC and then set stops depending on the amount I was filled at. If we consider the code from the example

`await bfx.ws.submit_order('tBTCUSD', 0, 1, 'EXCHANGE MARKET') `

Then since submit_order is returning None, the only way I see to get this information is to use a callback with the  'order_confirmed' decorator as follows:

```
@bfx.ws.on('order_confirmed')
async def trade_completed(order):
   # use order info

async def submit_order(auth_message):
    x = await bfx.ws.submit_order('tBTCUSD', 0, 0.0008, 'EXCHANGE MARKET')
   # How to use information from trade_completed
```
Now the issue I am having with this is, how can we pass the information received by trade_completed to submit_order? IIRC global variables do not work with asyncio. The only way would be to wrap all these co routines in a class but then one cannot use the decorators.

Am I missing something here?

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by JacobPlaster** [comment]
Hi, this is expected behavior. Websocket's are pretty much 'fire and forget' so Its hard to get a response in the same scope as the function call. However, there is actually a `callback` param that you can add which is called when an order update linked to the original submit is received.

```
def log_order(order):
    print (order)

await bfx.ws.submit_order('tBTCUSD', 0, 0.0008, 'EXCHANGE MARKET', onConfirm=log_order, onClose=log_order)
```
