### ISSUE TITLE
V2 Public Rest Endpoint Stats is not available through the library

### ISSUE THREAD

**Issue by lostless13** [bitfinexcom/bitfinex-api-py#59]
#### Issue type
- [ ] bug
- [x] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Public Rest Stats endpoint is not support: https://docs.bitfinex.com/reference#rest-public-stats1
#### Steps to reproduce
- Attempt to access stats endpoint

##### Additional Notes:
-

**Comment by JacobPlaster** [comment]
Thanks @lostless13 - we will add this to our TODO list
