### ISSUE TITLE
No event omited for ticker channel ws

### ISSUE THREAD

**Issue by mannguyen0107** [bitfinexcom/bitfinex-api-py#61]
#### Issue type
- [ ] bug
- [x] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
There is no event omited to get the result of ws ticker channel

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by JacobPlaster** [comment]
Fixed in https://github.com/bitfinexcom/bitfinex-api-py/pull/67
