### ISSUE TITLE
100% CPU consumption on simply subscribing to trades/candles etc

### ISSUE THREAD

**Issue by Shic1983** [bitfinexcom/bitfinex-api-py#65]
#### Issue type
- [1 ] performance

#### Brief description
Running a simple WS connection subscribing to a single tickers trades feed consumes 100% of CPU resources

#### Steps to reproduce
-
```
git clone repo
install
cd examples/ws
python subscribe_trades_candles.py
```
##### Additional Notes:
-
`top  [shift+m]` to see cpu usage
`pgrep -fa python` to see pid
`ps -o %cpu,%mem,cmd -p [pid]` to see singe line cpu output

show term link:
http://showterm.io/69795ac847f5c37f599bb

##### Looks to be..
https://github.com/bitfinexcom/bitfinex-api-py/blob/972e05eacd9c630d7333fecfd2bb59b5b872cae5/bfxapi/websockets/generic_websocket.py#L64

```
           await asyncio.sleep(0)
```

Personally I just changed this locally to sleep(0.01) and now my computer and breathe again and I dont have t o go to bed wondering if my computer will still be alive when i wake up

**Comment by JacobPlaster** [comment]
Hey @Shic1983 thanks for raising this issue and providing such a good description. I've made some changes in this PR which should solve your issue https://github.com/bitfinexcom/bitfinex-api-py/pull/66

With these changes, im only getting 4% CPU utilization when running the orderbook subscribe example.

**Comment by JacobPlaster** [comment]
Merged and published to https://pypi.org/project/bitfinex-api-py @ version 1.1.5
