### ISSUE TITLE
maintain available balance

### ISSUE THREAD

**Issue by Serpens66** [bitfinexcom/bitfinex-api-py#7]
Since release of ws v2 I'm trying to maintain real time availabe balance, since bitfinex is the only exchange worldwide that does not provide this in real time websocket. (Calling every av. balance via websocket takes over 1 minute, so maintaining it myself is the only way to go).
Beside being very very hard and complex, I still did not find any solution that works for all possible events.
Unfortunately neither the support, nor paolo itself were able or had the time to really answer the problems I showed them. I hope with releasing this libary, they finally solve this.

I think, that my current solution (that works nearly perfect) is already too complicated and there must be an easier way. So I ask you to provide code to maintain av. balance in all cases. If you can't, I can provide you my code and show you in which cases it still fails, so you can fix your websocket API.

**Comment by JacobPlaster** [comment]
Hi @Serpens66, you can achieve a realtime wallet balance by utilising the `wallet_update` event which is fired every single time that the balance of a wallet changes and when an authenticated websocket connection is opened then you are given your `wallet_snapshot` which includes all of you balances. Using these two events together you can maintaint he balance locally with perfect precision. see this code snippet:

```python
import os
import sys
sys.path.append('../')

from bfxapi import Client

API_KEY=os.getenv("BFX_KEY")
API_SECRET=os.getenv("BFX_SECRET")

balances = {}

bfx = Client(
  API_KEY=API_KEY,
  API_SECRET=API_SECRET,
  logLevel='INFO'
)

@bfx.ws.on('wallet_snapshot')
def log_snapshot(wallets):
  for wallet in wallets:
    balances[wallet.currency] = wallet.balance

@bfx.ws.on('wallet_update')
def log_update(wallet):
  balances[wallet.currency] = wallet.balance

bfx.ws.run()
```

**Comment by Serpens66** [comment]
If it would be that easy, I would have not spent a year+ :D

1) the wu update does not contain the available balance all the time, in 90% of the time it is just "None" (because bitfinex wants to save ressources.. cause "no one needs av. balance" :D).

2) "wu" does not include deposit/withdrawal/balance moved updates

This at least was true several months ago, please tell me if this improved meanwhile.

Of course I also wrote much with support of bitfinex and also with Paolo himself, but their priority is obviously something else...

> Hello Serpens66
> Hmm , that's a little weird as the 'wu' update message should include both the total balance as well as the available balance.
> If you are you not seeing that can you provide some examples of what you are seeing so I can talk to Paolo/dev team about this and see if there has been any updates or changes that may have affected this.
> As an additional option/check one thing you can do is whenever you see the wu/ws message come across you can also query the movements endpoint (https://docs.bitfinex.com/v2/reference#rest-auth-deposit-withdrawal-history) to get the list of recently completed deposits/withdrawals which you can use in your calculations

> Hi Support,
> Hm, so you don't have that deep API knowledge like I thought?
> The available balance entry is always "null" except I made the "calc" request shortly before. And since this calc request takes time, has to be done for every single currency and is limited to a number of currencies at once, this is absolutely useless for high frequency trading. Thats also why your additional option is also not usable, since when trading there will be hundreds of "wu" messages and I can not make another call everytime I see this.

> Quote https://docs.bitfinex.com/v2/reference#ws-auth-wallets:
> These messages have gained the ability to send the calculation values (available balance) equal to "null" meaning that the new calculated value is not yet available.
> In order to receive those values the user have to actively request for it with a "calc" message.
> See calc input dedicated section for more details.

> Since january 2018 I try to get an answer from Paolo or other API developers, but it seems they all are busy with other things (giving seminars and other bullshit wich is not related to bitfinex. I mean, seminars are good, but should not be made by the lead developer of bitfinex api, while there is enough work with the API)

did not receive any response to that since 4 months.

**Comment by JacobPlaster** [comment]
Thanks for the detailed description of the problem @Serpens66!

I can imagine that the balance withdrawal might a bit more tricky since they operate based on confirmations. For example bitfinex can issue the withdraw on their side but it wont necessarily take affect until the transaction has N number of confirmations on the chain. Ill have to take a look into how this is implemented on our end.
In regards to the wallet update only returning `None`, let me run some tests on that and get back to you.

**Comment by Serpens66** [comment]
@JacobPlaster 
Any news on this? Did the API from bitfinex improve meanwhile?
