### ISSUE TITLE
Get_active_position isn't working 

### ISSUE THREAD

**Issue by roman-hart** [bitfinexcom/bitfinex-api-py#71]
`await bfx.rest.get_active_position()` causes:
Error: __init__() takes 11 positional arguments but 21 were given

Also, does someone know how to handle _Unknown data event: 'pu'_ outside the _@bfx.ws.on('all')_ handler??

**Comment by ph4z** [comment]
> `await bfx.rest.get_active_position()` causes:
> Error: **init**() takes 11 positional arguments but 21 were given

It sounds there is something wrong in the way you instantiate the client.
The get_active_position() functions works well on my side.

> Also, does someone know how to handle _Unknown data event: 'pu'_ outside the _@bfx.ws.on('all')_ handler??

I have opened an new issue for this #74

**Comment by JacobPlaster** [comment]
@ph4z is correct, the bfx instance has not been initiated correctly. please paste more code.

@ph4z the issue that you are referencing has just been fixed in https://github.com/bitfinexcom/bitfinex-api-py/commit/84dd5d8d09c61eb16f5f46017f6e3e61e8091709
