### ISSUE TITLE
Handle 'pu' messages on websocket API

### ISSUE THREAD

**Issue by ph4z** [bitfinexcom/bitfinex-api-py#74]
#### Issue type
- [ ] bug
- [X] missing functionality
- [ ] performance
- [X] feature request

#### Brief description
You receive  `Unknown data event: 'pu'` on each 'pu' message

#### Steps to reproduce
- 

##### Additional Notes:
-

**Comment by JacobPlaster** [comment]
Fixed in https://github.com/bitfinexcom/bitfinex-api-py/commit/84dd5d8d09c61eb16f5f46017f6e3e61e8091709
