### ISSUE TITLE
Example doesn't run in Python 3.8

### ISSUE THREAD

**Issue by rht** [bitfinexcom/bitfinex-api-py#80]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description

I ran on python 3.8 the following example code (authenticate):
```python
import os
import sys
from bfxapi import Client, Order


bfx = Client(
  API_KEY='<YOUR_API_KEY>',
  API_SECRET='<YOUR_API_SECRET>'
)

@bfx.ws.on('authenticated')
async def do_something():
  print ("Success!")

bfx.ws.run()
```
I got this error
```
Traceback (most recent call last):
  File "crypto_trader.py", line 3, in <module>
    from bfxapi import Client, Order
  File "/home/rht/github/repos/bitfinex-api-py/bfxapi/__init__.py", line 6, in <module>
    from .client import Client
  File "/home/rht/github/repos/bitfinex-api-py/bfxapi/client.py", line 8, in <module>
    import asyncio
  File "/home/rht/code/venv/lib/python3.8/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/rht/code/venv/lib/python3.8/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
```

The fix is to not install `asyncio` on Python 3.8. There is a syntax for requirements.txt / setup.py as described in https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers, namely
`asyncio==3.4.3;python_version<'3.8'`

**Comment by soyelsimo** [comment]
`pip3 install bitfinex-api-py`

it installs asyncio in python >=3.8
unistall it won't make it work either downgrade pyee to 7.0.4 as state in #90

**Comment by itsdeka** [comment]
Fixed in latest version (https://github.com/bitfinexcom/bitfinex-api-py/issues/100).
This can be closed @prdn.

**Comment by rht** [comment]
But #100 is an issue, not a PR?
