### ISSUE TITLE
How to get current bitfinex datetime?

### ISSUE THREAD

**Issue by nkasimova** [bitfinexcom/bitfinex-api-py#85]
Hi!
 I'm getting tickers like this:
<code>     
    
    async def work():

        while True:

            ticker = await bfx.rest.get_public_ticker('tBTCUSD')

            print("Ticker:")

            print(ticker)

            await asyncio.sleep(1)

    loop = asyncio.get_event_loop()

    try:

        asyncio.ensure_future(work())

        loop.run_forever()

    except KeyboardInterrupt:

        pass

    finally:

        print("Closing Loop")

        loop.close()
</code>

How can I get a ticker's datetime?

**Comment by robertkowalski** [comment]
@nkasimova the current ticker is provided without a timestamp, internally it uses https://docs.bitfinex.com/reference#rest-public-ticker. it represents always the current state of the tickers
