### ISSUE TITLE
REST v2 missing symbol_details (not this library) 

### ISSUE THREAD

**Issue by Serpens66** [bitfinexcom/bitfinex-api-py#95]
#### Issue type
- [ ] bug
- [x] missing functionality
- [ ] performance
- [x] feature request

#### Brief description
The REST API v2 of bitfinex currently lacks a way to receive all relevant pair informations. Every single other exchange has such a call, but not bitfinex. I know the "Configs" (https://docs.bitfinex.com/reference#rest-public-conf), but the only promissing call, which is "pub:info:pair" is WIP and lacks alot of information.
**Please take my feedback and transform "pub:info:pair" into the perfect call to get all the information I'm looking for.**

What I want to get from such a call (now only talking about exchange/spot trading):
- All pairs traded on the exchange with status (if they are trading or halted/post_only/cancel_only or whatever. If bitfinex does not have those stati, you should implement them, since a serious exchange needs them).
- Assigned to each of these pairs, I need the base and the quote currency of each pair. Bitfinex does not use a seperator like "BTC_EUR", instead the pairs look like "tBTCEUR". In addition it is not guranteed that a pair always has 6 characters after this "t". That means it is impossible for the user to automatically identify the currencies involved in a pair. So you need to return this in an API call.
- In addition, I need all the trading details, like: min/max ordersize/quotesize/price and precision of price and also of amounts. (I think currently bitfinex has no "min/max quotesize". But I think it should implement it in exchange for min/max order sizes. minquotes fit much better for volatile cryptos.)

#### Steps to reproduce
-

##### Additional Notes:
- Feel free to contact me for more detailed feedback. I'm trading at over 15 other crypto exchanges since years and implemented their API. I think I know very well what a daytrader using REST needs. Bitfinex was one of the first exchanges I traded manually, but is one of the last I trade via API, because all my feedback was ignored and the API was(/is?) quite bad compared to other exchanges.

**Comment by Shic1983** [comment]
You're absolutely right.  The current 'method' to retreiving a complete list of information about what the exchange offers and such seems to involve at miniumum about 20 api calls (fGBP, how u going to normalise that volume to USD without knowing calc/fx/GBPUSD) .. etc . .    really, all this information should be available in a complete set just called, 'tickers' ..   

Also the lack of consistency between 'USD', 'USDT',' UST','USDF0' and  'tBTCUSD' and 'tBTC:USD' and so on just adds alot of technical debt overhead which really doesn't need to be there.

**Comment by bo198214** [comment]
This is marked as 'closed' but how do I retrieve base and quote currency for a pair?
I couldn't find anything suitable in the documentation (v2).

**Comment by bo198214** [comment]
is it that the crypto pairs always have 6 letters so first 3 is base and second 3 is quote and then you use pub:map:currency:sym?

**Comment by Serpens66** [comment]
dont know if anything new was added meanwhile (I doubt, the v2 API is just terrible to use).
I noted down that the support told me I should use this rule:
if the pair has 6 characters then use the first and second 3 characters to form the currencies. If it has a different number, then it will contain a ":" you can use to separate them.

**Comment by bo198214** [comment]
yes, as I supposed.
