### ISSUE TITLE
Automatically reconnects to unsubscribed channels

### ISSUE THREAD

**Issue by teresaejunior** [bitfinexcom/bitfinex-api-py#96]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description

After a WS disconnection (code 1006), BfxWebsocket automatically resubscribes to all channels, but the problem is it will also resubscribe to channels that were previously unsubscribed explicitly.

#### Steps to reproduce

1. Subscribe to an orderbook, and then unsubscribe with `await client.ws.unsubscribe(self.channel)`.
2. Wait for a disconnection. Due to high volumes these days, disconnections are happening many times a day.
3. Whatever function is set to run on `client.ws.on('order_book_update')` will start processing messages from the unsubscribed channel again.

##### Additional Notes:

I thought removing the channel_id manually from the subscription manager might work, but it gives me a KeyError:

    await self.ws.unsubscribe(self.channel)
    del(self.ws.subscriptionManager.subscriptions_chanid[self.channel])

**Comment by Shic1983** [comment]
In general I find unssubscribing confusing. 
If I subscribe, `bfx.ws.subscribe( 'trades', 'tBTCUSD')`
.. why can I not .. . `bfx.ws.unsubscribe( 'trades', 'tBTCUSD')` 
... doesn't make any sense.. same in.. same out.. . @JacobPlaster

**Comment by itsdeka** [comment]
Hello teresaejunior,
BfxWebsocket automatically resubscribes to all channels because the function you call with bfx.ws.on('connected', X)  does not take in consideration the fact you have unsubscribed.

Probably, if you are working on the examples available in this repository, you have this line in your code.

`bfx.ws.on('connected', start)`

The function start is executed every time you are disconnected and connected again.
I think that the most simple way to handle this thing is to conditionally subscribe to channels.

```
unsubscribed_channels = ['book_tBTCUSD']

async def start():
  if 'tBTCUSD' not in unsubscribed_channels:
     await bfx.ws.subscribe('book', 'tBTCUSD')
```

When you will want to unsubscribe permanently then you will use

```
bfx.ws.unsubscribe(channel)
unsubscribed_channels.append('book_tBTCUSD')
```

**Comment by teresaejunior** [comment]
Hi, thanks for your answer! Unfortunately, your assumptions are not correct!

1. With `self.ws.on('connected')`, I only have `logging.debug(msg)` lambda.
2. `self.ws.subscribe()` is already run conditionally, and the condition is simply not met when reconnecting.

I'll try increasing bfxapi's logging verbosity, and see if I can see anything between all the noise.

**Comment by teresaejunior** [comment]
OK, I've increased bfxapi's verbosity level to DEBUG, but I haven't found much on what's happening, but this problem is 100% reproducible. On my end, subscribing to the orderbook is logged with INFO, so I would have noticed any problems in my code long ago.

The only thing I have noticed is my attempt at `del(self.ws.subscriptionManager.subscriptions_chanid[self.channel])` wouldn't have made any difference, since it resubscribes always with a different chanId.

If you need any more info on my part, I may provide. @robertkowalski or @itsdeka please reopen. Thanks!
