### ISSUE TITLE
can't register atexit after shutdown thrown in Python 3.9

### ISSUE THREAD

**Issue by xJayMorex** [bitfinexcom/bitfinex-api-py#97]
#### Issue type
- [X] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description

Example code doesn't run since Python 3.9.

#### Steps to reproduce
- Run any example code with Python 3.9 installed

##### Additional Notes:
- Error "can't register atexit after shutdown" is thrown.

**Comment by robertkowalski** [comment]
hi @xJayMorex, thanks for reporting. we'll fix as soon as possible

**Comment by robertkowalski** [comment]
fixed in current master :)

**Comment by xJayMorex** [comment]
Thanks!

**Comment by TouriM** [comment]
Any plans to push 1.1.9 as a official release?
